
<div class="container privacy-policy">
	<h6>SafeWay Privacy Statement</h6>
	<p>Your privacy is very important to us. We will not sell your information to a third party outside of our SafeWay Driving family of businesses for any reason. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate, disclose and make use of personal information. Before or at the time of collecting personal information, we will identify the purposes for which information is being collected. We will collect and use personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law. We will only retain personal information as long as necessary for the fulfillment of those purposes and as required by the State of Texas to deliver driver training.</p>
	<p>We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. SafeWay Driving automatically receives and records information on our server logs from your browser, including IP addresses, browser types, referrer pages, domain names, access times, entry pages, exit pages, operating system types and search engine keywords used.
	</p>
	<p>SafeWay Driving uses the information it collects to identify the most effective ways to reach you, the customer, to more effectively meet your needs with regards to new products and services, and to contact you about product upgrades. SafeWay Driving reserves the right to gather general statistic information such as number of users, aggregate and non-personally identifiable demographic data, number and type of goods and services purchased, etc., for SafeWay Driving’ business and marketing purposes.</p>
	<p>If you have chosen to receive email and/or text communications, you will receive emails and/or texts pertinent to your account, your schedule and other information and announcements from SafeWay Driving.</p>
	<p>SafeWay Driving is the sole owner of the information collected on its web site and will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification. We will make readily available to customers information about our policies and practices relating to the management of personal information. We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.</p>

	<h6>Security</h6>
	<p>SafeWay Driving takes every precaution in protecting your personal information. Your SafeWay Driving account is password-protected for security and privacy purposes. We are PCI compliant and use SSL encryption to protect sensitive information online. Additionally, SafeWay Driving does not store any financial information on any of our databases after it has been processed. All employees are trained and updated on our security and privacy policies.
	</p>

	<h6>Changing and Editing Your Personal Information</h6>
	<p>SafeWay Driving allows you at any time to change the personal information you provided to us at the time of your registration. To edit this information, log into your secure account and make the appropriate changes to your personal information.</p>

</div>